### ISSUE TITLE
Download button does not appear on uploading large number of SVG

### ISSUE THREAD

**Issue by Matt4880** [filamentgroup/grumpicon#62]
Attempting to drag-drop 128 SVG files onto GrumpIcon results in displaying all of the SVG icons and the 'preview files' option underneath them but no download button. Seen in IE 10, Firefox and Chrome. It is possible to work around by dragging 1 SVG then adding the rest, although this results in a lot of JS errors (prob 1 per file, but unconfirmed):

grumpicon.min.js:9 Uncaught TypeError: Cannot read property 'replace' of undefined
    at http://www.grumpicon.com/public/dist/grumpicon.min.js:9:10598
    at Function.p.each.p.forEach (http://www.grumpicon.com/public/dist/grumpicon.min.js:8:20029)
    at b.o.(anonymous function) [as each] (http://www.grumpicon.com/public/dist/grumpicon.min.js:1:12042)
    at b.value (http://www.grumpicon.com/public/dist/grumpicon.min.js:9:10534)
    at k (http://www.grumpicon.com/public/dist/grumpicon.min.js:1:2476)
    at b.trigger (http://www.grumpicon.com/public/dist/grumpicon.min.js:1:1850)
    at Object.<anonymous> (http://www.grumpicon.com/public/dist/grumpicon.min.js:9:21557)
    at Object.<anonymous> (http://www.grumpicon.com/public/dist/grumpicon.min.js:4:25623)
    at k (http://www.grumpicon.com/public/dist/grumpicon.min.js:4:24255)
    at Object.fireWith [as resolveWith] (http://www.grumpicon.com/public/dist/grumpicon.min.js:4:25067)

Just dropping the files without the first step just has multiple JS errors with the same callstack

**Comment by Matt4880** [comment]
OK - the workaround didn't work - you only get the one file you originally dragged, not all the new ones

**Comment by Matt4880** [comment]
After looking again at my source SVGs there were some other data in it coming from Adobe that seemed to break the website. Removing these gave me back my download button.

The Javascript errors were still being reported though, so that may be something that someone needs to look into?
